### ISSUE TITLE
keepass-plugin-favicon: "Specified cast is not valid."

### ISSUE THREAD

**Issue by 2chg** [dtgm/chocolatey-packages#167] opened 2016-03-29 13:18 UTC
Whenever I try to install the **keepass-plugin-favicon** package on a _Windows 10 Pro_ system the installation aborts with the following error:

```
> choco install -y keepass-plugin-favicon
Installing the following packages:
keepass-plugin-favicon
By installing you accept licenses for the packages.

keepass-plugin-favicon v1.9.0
 Specified cast is not valid.
 At C:\ProgramData\chocolatey\lib\keepass-plugin-favicon\tools\chocolateyInstall.ps1:66 char:3
 +   throw $_.Exception
 +   ~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : OperationStopped: (:) [], InvalidCastException
     + FullyQualifiedErrorId : Specified cast is not valid.
The install of keepass-plugin-favicon was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\keepass-plugin-favicon\tools\chocolateyInstall.ps1'.
 See log for details.

Chocolatey installed 0/1 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - keepass-plugin-favicon
```

**Comment by dtgm** [comment] 2016-06-18 21:01
Caused by a bad registry key created by another program. Please copy paste the following code and let me know which program it is.

```powershell
$hkcu = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*'
$hklm = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*'
$hklmWow = 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*'
[array]$keys = Get-ChildItem -Path @($hkcu, $hklm, $hklmWow) -ea SilentlyContinue
[bool]$success = $FALSE
[int]$maxAttempts = 10
for ([int]$attempt = 1; $attempt -le $maxAttempts; $attempt++) {
  try {[array]$foundKey = Get-ItemProperty -Path $keys.PsPath -ea SilentlyContinue | ?{$_.DisplayName -like "*"}; $success = $TRUE;}
  catch {
    foreach ($key in $keys){
      try{Get-ItemProperty $key.PsPath > $null}
      catch{$badKey = $key.PsPath}
    }
  Write-Warning "Found bad key: $badKey"
  [array]$keys = Get-ChildItem -Path @($hkcu, $hklm, $hklmWow) -ea SilentlyContinue | ?{$badKey -NotContains $_.PsPath}
  }
  if ($success) {break;}
}
```
details about why in #92 
general solution in #198, and will be implemented specifically for this pkg in #222 

As you may have noticed, this bug affects many packages on chocolatey.org and most all install packages I maintain. This will be slowly snuffed out as old packages get updated. For now, the workaround is to remove the offending application, or, if you need the offending software installed, fix the bad registry key.

**Comment by 2chg** [comment] 2016-08-02 06:09
Hello,


sorry for the late anwser.

The given script returns the following „bad“ registry key:

> WARNING: Found bad key:
> Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\nbi-nb-base-8.1.0.0.201510222201


What do you think I should do next?


Sincerely yours

    Christian

**Comment by tunisiano187** [comment] 2020-08-01 19:16
@gep13 , this plugin isn't mainained anymore (last update 2016)
and the problem isn't really related to the package but more to the plugin itself.
so i think you can close it too.
Thank you

**Comment by gep13** [comment] 2020-08-02 20:44
@tunisiano187 :+1:

**Closed by gep13** 2020-08-02 20:44 UTC
